package core

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// LocalEmit is the LOCAL follower's framer — the in-process counterpart to Reframe
// (the relay framer). The P2.4 gate (reviewer + D6):
//
//   (1) On the PARITY domain (all fields present as strings, non-empty text, no
//       kind) LocalEmit(line) is byte-exact vs the lifted bash emit() — reusing the
//       existing corpus.golden — AND equals Reframe(line)+"\n". The kind=presence
//       class, which the relay drops, RETURNS to scope locally: it is pinned in its
//       own golden (corpus_local.golden), generated by the same lifted emit().
//   (2) Degenerate inputs follow ruling D6, NOT the bash follower verbatim — pinned
//       in TestLocalEmitDivergenceMatrix, never in a golden corpus (they would fail
//       parity by design, since the lifted emit() has bash's None-leak).
//   (3) Reframe stays byte-untouched (frame_test.go / golden_test.go unedited, green).
//   (4) LocalEmit and Reframe share frameHead/frameBody/wrapBytes — no second wrap.

// walkGolden asserts LocalEmit(line) equals the golden block for each corpus line,
// consuming the golden message-by-message (each block is LocalEmit's bytes verbatim,
// including its single trailing '\n').
func walkGolden(t *testing.T, corpusFile, goldenFile string) {
	t.Helper()
	corpus, err := os.ReadFile(filepath.Join("testdata", corpusFile))
	if err != nil {
		t.Fatal(err)
	}
	golden, err := os.ReadFile(filepath.Join("testdata", goldenFile))
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(strings.TrimRight(string(corpus), "\n"), "\n")
	off := 0
	for i, line := range lines {
		want := LocalEmit([]byte(line))
		if off+len(want) > len(golden) || !bytes.Equal(golden[off:off+len(want)], want) {
			end := off + len(want)
			if end > len(golden) {
				end = len(golden)
			}
			t.Fatalf("message %d diverges from LocalEmit(line)\n line:   %.80q\n want:   %q\n golden: %q",
				i, line, want, golden[off:end])
		}
		off += len(want)
	}
	if off != len(golden) {
		t.Fatalf("%s has %d unexpected trailing bytes after %d messages", goldenFile, len(golden)-off, len(lines))
	}
}

// TestLocalEmitGoldenParity: on the plain parity domain LocalEmit is byte-exact vs
// the lifted bash emit() (corpus.golden IS emit()'s output, one trailing '\n' per
// message — exactly what a local write is). Reuses the relay corpus, proving the
// local and relay framers agree there.
func TestLocalEmitGoldenParity(t *testing.T) {
	walkGolden(t, "corpus.jsonl", "corpus.golden")
}

// TestLocalEmitPresenceGolden: the kind=presence class the relay drops but the local
// follower keeps, pinned to its own lifted-emit() golden (kind rendered in the
// header, event stored-not-rendered, body wrapped under the kind header).
func TestLocalEmitPresenceGolden(t *testing.T) {
	walkGolden(t, "corpus_local.jsonl", "corpus_local.golden")
}

// TestLocalEmitParityEqualsReframe pins the shared-internals contract on the parity
// domain: LocalEmit(line) == Reframe(line)+"\n", byte-exact. (Holds because no plain
// corpus line exceeds WSFrameSafe, so the relay ⚠ warning — which the local follower
// never emits — never fires; TestGoldenCorpusParity guards that premise.) Any change
// that forks the two framers' wrap/marker handling breaks this.
func TestLocalEmitParityEqualsReframe(t *testing.T) {
	corpus, err := os.ReadFile(filepath.Join("testdata", "corpus.jsonl"))
	if err != nil {
		t.Fatal(err)
	}
	for i, line := range strings.Split(strings.TrimRight(string(corpus), "\n"), "\n") {
		want := append(Reframe([]byte(line)), '\n')
		got := LocalEmit([]byte(line))
		if !bytes.Equal(got, want) {
			t.Fatalf("message %d: LocalEmit != Reframe+\\n\n line: %.80q\n local: %q\n relay: %q", i, line, got, want)
		}
	}
}

// TestLocalEmitPresenceCrossParse is the D8 presence rider for the LOCAL path: a
// canonical-Go presence line (compact, HTML-escaping on) and its spaced python-style
// equivalent frame BYTE-IDENTICALLY, because LocalEmit frames the PARSED values, not
// the raw bytes. So a Go-marshaled presence line delivers exactly like a bash-written
// one during coexistence.
func TestLocalEmitPresenceCrossParse(t *testing.T) {
	type presence struct {
		From  string `json:"from"`
		To    string `json:"to"`
		TS    string `json:"ts"`
		Kind  string `json:"kind"`
		Event string `json:"event"`
		Text  string `json:"text"`
	}
	p := presence{From: "ch/orch", To: "ch/mbp", TS: "t", Kind: "presence", Event: "join", Text: "joined ch as orch <b> & c"}
	goBytes, err := json.Marshal(p) // compact, escapes <>&
	if err != nil {
		t.Fatal(err)
	}
	pyBytes := []byte(`{"from": "ch/orch", "to": "ch/mbp", "ts": "t", "kind": "presence", "event": "join", "text": "joined ch as orch <b> & c"}`)
	if bytes.Equal(goBytes, pyBytes) {
		t.Fatal("cross-parse test is vacuous: the two encodings are byte-identical")
	}
	if a, b := LocalEmit(goBytes), LocalEmit(pyBytes); !bytes.Equal(a, b) {
		t.Fatalf("presence cross-parse diverged\n go: %q\n py: %q", a, b)
	}
	// and the rendered frame keeps kind, drops event, renders text as the body.
	got := string(LocalEmit(goBytes))
	if strings.Contains(got, "event=") || strings.Contains(got, "\njoin\n") {
		t.Fatalf("event must not render: %q", got)
	}
	if !strings.HasPrefix(got, "◀ cbus msg from=ch/orch to=ch/mbp ts=t kind=presence\n") {
		t.Fatalf("bad presence header: %q", got)
	}
}

// TestLocalEmitDivergenceMatrix pins the LOCAL follower's degenerate column per
// ruling D6 — deliberately NOT bash emit() verbatim. Compare with the relay column
// in frame_test.go:TestReframeDivergenceMatrix: the passthrough set is identical
// (D6 == Reframe's all-or-nothing gate) EXCEPT (a) every local write ends in one
// '\n', and (b) a framed line with missing from/to renders "?" (Reframe renders them
// empty) so the local display column is never blank. Empty/null text passing THROUGH
// is the None-leak fix (bash frames "None"/an empty body instead).
func TestLocalEmitDivergenceMatrix(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string // passthrough cases: in + "\n"; framed cases: the block + "\n"
	}{
		{"D6 empty text -> passthrough",
			`{"from":"c/o","to":"c/a","ts":"t","text":""}`,
			`{"from":"c/o","to":"c/a","ts":"t","text":""}` + "\n"},
		{"D6 missing text -> passthrough",
			`{"from":"c/o","to":"c/a","ts":"t"}`,
			`{"from":"c/o","to":"c/a","ts":"t"}` + "\n"},
		{"D6 null text -> passthrough (fixes bash None-leak)",
			`{"from":"c/o","to":"c/a","ts":"t","text":null}`,
			`{"from":"c/o","to":"c/a","ts":"t","text":null}` + "\n"},
		{"D6 non-string text -> passthrough",
			`{"from":"c/o","to":"c/a","ts":"t","text":123}`,
			`{"from":"c/o","to":"c/a","ts":"t","text":123}` + "\n"},
		{"D6 non-string from -> passthrough (any non-string field aborts)",
			`{"from":123,"to":"c/a","ts":"t","text":"hi"}`,
			`{"from":123,"to":"c/a","ts":"t","text":"hi"}` + "\n"},
		{"D6 non-dict JSON -> passthrough",
			`[1,2,3]`, "[1,2,3]\n"},
		{"D6 from/to missing, text ok -> framed with ? (keeps local column)",
			`{"ts":"t","text":"hi"}`,
			"◀ cbus msg from=? to=? ts=t\nhi\n◀ cbus end from=?\n"},
		{"D6 from/to missing + kind -> framed with ? and kept kind",
			`{"ts":"t","text":"hi","kind":"presence"}`,
			"◀ cbus msg from=? to=? ts=t kind=presence\nhi\n◀ cbus end from=?\n"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := string(LocalEmit([]byte(c.in))); got != c.want {
				t.Errorf("LocalEmit(%s)\n got  %q\n want %q", c.in, got, c.want)
			}
		})
	}
	// an empty inbox line emits nothing at all (not even a newline).
	if got := LocalEmit([]byte("")); got != nil {
		t.Errorf("empty line: got %q, want nil", got)
	}
	if got := LocalEmit([]byte("\n")); got != nil {
		t.Errorf("bare newline: got %q, want nil", got)
	}
	// the "?" placeholder is a real divergence FROM Reframe (which renders blank).
	if bytes.Equal(LocalEmit([]byte(`{"ts":"t","text":"hi"}`)), append(Reframe([]byte(`{"ts":"t","text":"hi"}`)), '\n')) {
		t.Error("D6: missing from/to must render \"?\" locally but blank on the relay — they must differ")
	}
}
